<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>form_search</name>
   <tag></tag>
   <elementGuidId>0d8b3b48-6918-40ae-94c8-ee8c6a511c79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>form[action=&quot;/search&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
