<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search</name>
   <tag></tag>
   <elementGuidId>c173feb7-74ef-450d-8e9b-1965ce89e490</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name='q']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'q']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>q</value>
   </webElementProperties>
</WebElementEntity>
